# -*- coding: utf-8 -*-
"""Dose_response_antagonists_for_PUBLICATION.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NgoYSlsFplV2H1hCwyhD6HeEHh-N59tT

# **TEVC - Dose Response**

## Set up libraries
"""

import pandas as pd
import numpy as np
import glob as glob

"""## Import and prepare data

### Mount google drive (optional)

comment out if you want to load data from hard drive
"""

from google.colab import drive
drive.mount('/content/drive', force_remount=True)

"""### Import Files

Import all files from specified folder and combine into one dataframe called 'df'
"""

path = r'drive/your_path_to_folder_here' # use your path
all_files = glob.glob(path + "/*_Datatable.csv") # use your extension

li = []

for filename in all_files:
    df = pd.read_csv(filename, index_col=None, header=0) # for .dat files you must specify separation for example sep='\t'
    li.append(df)

df = pd.concat(li, axis=0, ignore_index=True)

df.shape
#df.head()

"""### Remove excess coloumns and clean data
Here we are keeping only the relevant information, you can add or remove coloumns as you like.
We will also be standardising the units and generally cleaning up the data
"""

#coloumn names must be updated to those in your files, these are based on the standard coloumn titles from Robocyte2+ software export
data =  df[['Inj. ID 1'] + ['Well'] + ['Buffer'] + ['Comp. 1'] + ['conc. 1'] + ['unit 1'] + ['Minimum'] + ['Baseline Average'] + ['Start Date'] + ['Comp. 2'] + ['conc. 2'] + ['unit 2']]

data['date'] = data['Start Date'].str.extract('(../../....)', expand=True)

data.head()

"""Transform units all to uM scale"""

#Transform units all to µM scale
conditions = [
    (data['unit 1'] == 'mM'),
    (data['unit 1'] == 'µM'),
    (data['unit 1'] == 'nM')]
choices = ['1000', '1', '0.001']
data['factor'] = np.select(conditions, choices, default='0')

data['factor']=data.factor.astype(float)

data['Comp1_Concentration_µM'] = data['conc. 1'] * data['factor']

conditions = [
    (data['unit 2'] == 'mM'),
    (data['unit 2'] == 'µM'),
    (data['unit 2'] == 'nM')]
choices = ['1000', '1', '0.001']
data['factor'] = np.select(conditions, choices, default='0')

data['factor']=data.factor.astype(float)

data['Comp2_Concentration_µM'] = data['conc. 2'] * data['factor']

data =  data[['Inj. ID 1'] + ['Well'] + ['Buffer'] + ['Comp. 1'] + ['Comp. 2'] + ['Minimum'] + ['Comp2_Concentration_µM'] + ['date'] + ['Comp1_Concentration_µM']]
data.reset_index(drop=True)
                         
data.head()

#decide if comp1 or comp2 is agonist or antagonsit
data['Antagonist'] = data['Comp. 1']
data['Agonist'] = data['Comp. 2']

data['Response'] = data['Minimum']
data['Agonist_µM'] = data['Comp2_Concentration_µM']
data['Antagonist_µM'] = data['Comp1_Concentration_µM']

data = data.drop(columns=['Comp. 2'])
data = data.drop(columns=['Comp. 1'])
data = data.drop(columns=['Comp2_Concentration_µM'])
data = data.drop(columns=['Comp1_Concentration_µM'])

data.head()

"""## Transform data to I/Imax for each oocyte"""

minvalues = data.groupby(['Well', 'date', 'Antagonist'])["Minimum"].min()
norm = data.Minimum / data.groupby(['Well', 'Antagonist']).Minimum.transform(np.min)
data['Response'] = norm
data.drop(columns=['Minimum', 'Buffer'])
data.head()

grouped_data = data.groupby(['Antagonist', 'Antagonist_µM']) #view grouped data
grouped_data['Response'].describe()

"""## Export as .csv
comment out if you do not want to export .csv
change path and file name before running

exports grouped mean, std, N into a new .csv file

Includes *injection ID*, Agonist and log agonist concentrations in uM
"""

export = data #select data to export
export = data.groupby(['Antagonist', 'Antagonist_µM']) #select groups to average
export = export['Response'].describe()
#export = export.loc[export['Agonist_Concentration_µM'] == 5.000] #if you wish to export a single dose
export.head(15) #if you wish to view the exported data
#export.to_csv(r'drive/where_you_want_your_file/export.csv')